# Mancer Systemd Prototype - Konfiguracja
# Plik konfiguracyjny z ustawieniami TUI i systemd

# Ustawienia interfejsu TUI
ui:
  theme: "default"
  colors:
    primary: "blue"
    secondary: "green"
    warning: "yellow"
    error: "red"
    success: "green"
    info: "cyan"
  
  # Skróty klawiszowe
  shortcuts:
    quit: "q"
    refresh: "r"
    search: "/"
    filter: "f"
    help: "h"
    back: "b"
    next: "n"
    previous: "p"
    select: "Enter"
    toggle: "Space"
  
  # Ustawienia wyświetlania
  display:
    auto_refresh: true
    refresh_interval: 5  # sekundy
    show_timestamps: true
    show_icons: true
    compact_mode: false

# Ustawienia systemd
systemd:
  # Typy jednostek do wyświetlania
  unit_types:
    - "service"
    - "socket"
    - "target"
    - "timer"
    - "mount"
    - "automount"
    - "swap"
    - "path"
    - "slice"
    - "scope"
  
  # Statusy do filtrowania
  statuses:
    - "active"
    - "inactive"
    - "failed"
    - "dead"
    - "exited"
    - "running"
    - "stopped"
  
  # Akcje dostępne dla jednostek
  actions:
    start: "start"
    stop: "stop"
    restart: "restart"
    reload: "reload"
    enable: "enable"
    disable: "disable"
    mask: "mask"
    unmask: "unmask"
    status: "status"
    show: "show"
  
  # Lokalizacje plików konfiguracyjnych
  config_paths:
    - "/etc/systemd/system/"
    - "/usr/lib/systemd/system/"
    - "/run/systemd/system/"
    - "/usr/local/lib/systemd/system/"

# Ustawienia SSH
ssh:
  timeout: 30
  retry_attempts: 3
  key_file: "~/.ssh/id_rsa"
  known_hosts: "~/.ssh/known_hosts"
  
# Ustawienia logowania
logging:
  level: "INFO"
  file: "mancer-systemd.log"
  max_size: "10MB"
  backup_count: 5
  
# Ustawienia cache
cache:
  enabled: true
  ttl: 300  # sekundy
  max_size: 1000
  
# Ustawienia raportów
reports:
  output_dir: "./reports"
  format: "txt"  # txt, json, yaml
  include_timestamp: true
  include_metadata: true
